{% set version = '1.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-azuregraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AzureGraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AzureGraph/AzureGraph_{{ version }}.tar.gz
  sha256: 07cbc5483e06dacd9a28faff92bb99884dd68a8abdcf2743381a255e00bd97a7

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-azureauth >=1.0.1
    - r-r6
    - r-curl
    - r-httr >=1.3
    - r-jsonlite
    - r-openssl
  run:
    - r-base
    - r-azureauth >=1.0.1
    - r-r6
    - r-curl
    - r-httr >=1.3
    - r-jsonlite
    - r-openssl

test:
  commands:
    - $R -e "library('AzureGraph')"           # [not win]
    - "\"%R%\" -e \"library('AzureGraph')\""  # [win]

about:
  home: https://github.com/Azure/AzureGraph https://github.com/Azure/AzureR
  license: MIT
  summary: 'A simple interface to the ''Microsoft Graph'' API <https://docs.microsoft.com/en-us/graph/overview>.
    ''Graph'' is a comprehensive framework for accessing data in various online Microsoft
    services. This package was originally intended to provide an R interface only to
    the ''Azure Active Directory'' part, with a view to supporting interoperability
    of R and ''Azure'': users, groups, registered apps and service principals. However
    it has since been expanded into a more general tool for interacting with Graph.
    Part of the ''AzureR'' family of packages.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: AzureGraph
# Title: Simple Interface to 'Microsoft Graph'
# Version: 1.3.2
# Authors@R: c( person("Hong", "Ooi", , "hongooi73@gmail.com", role = c("aut", "cre")), person("Microsoft", role="cph") )
# Description: A simple interface to the 'Microsoft Graph' API <https://docs.microsoft.com/en-us/graph/overview>. 'Graph' is a comprehensive framework for accessing data in various online Microsoft services. This package was originally intended to provide an R interface only to the 'Azure Active Directory' part, with a view to supporting interoperability of R and 'Azure': users, groups, registered apps and service principals. However it has since been expanded into a more general tool for interacting with Graph. Part of the 'AzureR' family of packages.
# URL: https://github.com/Azure/AzureGraph https://github.com/Azure/AzureR
# BugReports: https://github.com/Azure/AzureGraph/issues
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# Depends: R (>= 3.3)
# Imports: AzureAuth (>= 1.0.1), utils, httr (>= 1.3), jsonlite, openssl, curl, R6
# Suggests: AzureRMR, vctrs, knitr, rmarkdown, testthat
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-11-27 11:34:29 UTC; hongo
# Author: Hong Ooi [aut, cre], Microsoft [cph]
# Maintainer: Hong Ooi <hongooi73@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-11-28 10:10:02 UTC
